### PR TITLE
More leftovers from previous checkins

### PR DESCRIPTION
**Pull request by Mellvik**
Also includes `ne2k` support for setting the global `running_qemu`.

### CODE REVIEW

**Comment by ghaerr** [comment]
The main.c overwrite bug fix looks good, but I found a calculation problem in exactly figuring when the envp_init array gets overwritten, changed (again) in https://github.com/ghaerr/elks/pull/1976. I also decreased the size of the very-seldomly seen panic text strings.

This won't affect the rabbit we're chasing on TLVC, so go ahead and commit this.

**Comment by Mellvik** [comment]
Thank you, @ghaerr.
About the panics, I'm not sure a panic is the right choice when encountering bootopts errors. A panic makes it impossible for the user to fix the problem 'locally' on the platform. If the process to get to that point was cumbersome, that's unfortunate. 

Of course it is also unfortunate with a warning that scrolls off the screen. Thus I've been pondering a different approach, a delayed error message emitted just before passing control to process 1. That way the handling of oversized bootopts files could be made more  lenient too.

what's your take?

**Comment by ghaerr** [comment]
> what's your take?

I had almost the same sequence of thoughts as you're having on this. Actually, the data overwrite issue occurs extremely rarely, and only occurred because ELKS was seeing the long hdparms= and le0= strings from a TLVC (non-ELKS) bootopts as environment variables rather than parsing them. So on almost every system, these issues will never arise.

I don't like panic, and was thinking of writing a bunch of extra code to deal with getting a keystroke, etc but this occurs extremely early in the kernel init. The previous code checked for args or envs > 8 and silently ignored them (worse), but didn't check the args string length overrun. 


I finally decided on using as little code and data as possible (the code is INITSEG but the data arrays[] stay in the kernel data segment forever), since these three error messages will almost likely never happen again. I do realize that means one might have to rebuild the image on a host, but we seem to do that a lot nowadays anyways.

> That way the handling of oversized bootopts files could be made more lenient too.

Yes, I'm pretty sure that message has scrolled by many times unnoticed. However, people usually will continue to play with settings until they get them right. I initially thought about making this a panic too and realized that would be a disaster. 

Ultimately, I don't think adding a bunch of extra code is worth much. If the a BIOS character wait were added, then the system gains one more dependency and could also just sit and not remotely boot, requiring human intervention anyways. Having a timeout doesn't really notify the user if they're not staring at the console during boot. So I figured in the rare case that /bootopts would cause corruption or not work as intended, its better just to stop the boot so the user know for sure somethings broken.

On another note, ELKS and TLVC bootopts aren't compatible, ELKS uses task=, TLVC tasks=, etc etc. So the whole idea of sharing is lost and copying a /bootopts file from one system to another will produce undesired results with no error messages at all. We can consider more of this issue after the long-stacked problem of getting the NIC drivers compatible is resolved, I would say! :)

**Comment by Mellvik** [comment]
> 
> I don't like panic, and was thinking of writing a bunch of extra code to deal with getting a keystroke, etc but this occurs extremely early in the kernel init. The previous code checked for args or envs > 8 and silently ignored them (worse), but didn't check the args string length overrun.
> 
> I finally decided on using as little code and data as possible (the code is INITSEG but the data arrays[] stay in the kernel data segment forever), since these three error messages will almost likely never happen again. I do realize that means one might have to rebuild the image on a host, but we seem to do that a lot nowadays anyways.

My idea is to skip both the panic and the message - assuming to scrolls off the screen anyway (the smart ones film the boot sequence with their phones to get everything :-) ), and instead see a simple global int bit vector where a bit is set depending on which error happened. That vector can then be simply decoded and messages emittelike just before or after kernel_banner, ensuring its visibility.

As to rebuild versus letting it boot: On real hardware the situation is entirely different. A new image may take 5 or more minutes to build, transfer, copy, swapping floppies back and forth between systems, and in my case (which admittedly is rare) a trip to the garage and back. Letting `bootopts` errors softfail into a booted system (of course the error may be too severe to boot, but in most cases it isn't) is actually quite a big deal.

> 
> On another note, ELKS and TLVC bootopts aren't compatible, ELKS uses task=, TLVC tasks=, etc etc. So the whole idea of sharing is lost and copying a /bootopts file from one system to another will produce undesired results with no error messages at all. We can consider more of this issue after the long-stacked problem of getting the NIC drivers compatible is resolved, I would say! :)

Yes, there are a few incompatibilities and it's worthwhile working on that. I chose the plural forms `bufs=` and `tasks=`, sacrificing a byte in both cases, because  it's easier to understand - to new users in particular. The plural form invites a number, the singular form is less obvious. I suggest doing the same with all `bootopts` keywords expecting a number (inodes=, files=, xmsbufs= etc.) . And yes, I agree that this belongs under the 'general' (wow, sounds serious!) compatibility tab of our worklist. Anyway, think about it.

**Comment by ghaerr** [comment]
> and instead see a simple global int bit vector where a bit is set depending on which error happened. That vector can then be simply decoded and messages emittelike just before or after kernel_banner, ensuring its visibility.

The error checking occurs in different functions, but I like the idea of later visibility. I'll look into this good idea also, with an attempt at minimal code addition.

**Pull request merged**
